[package]
name = "renrs-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renrs-extensions.workspace = true
renrs-model.workspace = true
renrs-syntax.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
thiserror.workspace = true
sha2.workspace = true

[dev-dependencies]
renrs-compiler.workspace = true

[lints]
workspace = true
