[package]
name = "renrs-extensions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renrs-syntax.workspace = true
rhai = { version = "1.23", default-features = false, features = ["std", "sync", "serde", "no_float", "no_time", "only_i64"] }

[lints]
workspace = true
