[package]
name = "renrs-project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renrs-compiler.workspace = true
renrs-extensions.workspace = true
renrs-model.workspace = true
renrs-shared = { workspace = true, features = ["hash", "io"] }
renrs-syntax.workspace = true
indexmap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tempfile.workspace = true

[lints]
workspace = true
