pub mod analysis;
pub mod compiler;
pub mod expression;
pub mod localization;
pub mod parser;
pub mod progress;
pub use analysis::analyze;
pub use compiler::{CompileError, InstructionId, Program, StatementId, compile};
pub use diagnostic::Diagnostic;
pub use localization::{Localizer, TranslationCatalog, TranslationId};
pub use parser::parse_script;
pub use renrs_syntax::{diagnostic, syntax, text};
