mod app;
mod asset_worker;
mod assets;
mod audio;
mod audio_worker;
mod benchmark;
mod bootstrap;
mod byte_budget;
mod dialogue;
mod image_layers;
mod media;
mod metrics;
mod options;
mod reload;
mod reload_worker;
mod render;
mod saving;
mod settings;
mod smoke;
mod speech;
mod stage_camera;
mod story;
mod text;
mod ui_accessibility;
mod ui_collection;
mod ui_common;
mod ui_composition;
mod ui_declarative;
mod ui_history;
mod ui_languages;
mod ui_layouts;
mod ui_menu;
mod ui_overlays;
mod ui_save_tools;
mod ui_screen_actions;
mod ui_screen_controls;
mod ui_screen_lists;
mod ui_slots;
mod ui_text;
mod ui_toolbar;
mod video_audio;
mod video_worker;
mod wake;

pub(crate) use bootstrap::{run, window_conf};

pub(super) const CANVAS_WIDTH: f32 = 1280.0;
pub(super) const CANVAS_HEIGHT: f32 = 720.0;
