[package]
name = "renrs-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renrs-syntax.workspace = true
indexmap.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[lints]
workspace = true
