[package]
name = "renrs-syntax"
version = "0.1.0-rc.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[dependencies]
indexmap = { version = "2.11", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
thiserror = "2"
intl_pluralrules = "7"
unic-langid = "0.9"

[lints]
workspace = true
