[package]
name = "renrs-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
thiserror.workspace = true
intl_pluralrules = "7"
unic-langid = "0.9"
velin-syntax.workspace = true

[lints]
workspace = true
