[package]
name = "renrs-shared"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["hash", "io"]
hash = ["dep:hex", "dep:serde", "dep:serde_json", "dep:sha2"]
io = ["dep:serde", "dep:serde_json", "dep:tempfile"]

[dependencies]
hex = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }

[lints]
workspace = true
