[package]
name = "renrs-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renrs-compiler.workspace = true
renrs-project.workspace = true
renrs-syntax.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
url = "2.5"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
